amcl:
  ros__parameters:
    use_sim_time: True
    map_type: 'occupancy'
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    do_beamskip: false
    laser_likelihood_max_dist: 2.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    behavior_tree_plugins: "nav2_behavior_tree_nodes"
    goal_blackboard_id: "goal"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "<path_to_your_map_file>"

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]

recoveries_server:
  ros__parameters:
    use_sim_time: True
    recovery_plugins: ["Spin", "BackUp", "Wait"]

# Add additional parameters as needed
